version: "3"
services:
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3307:3306"
        env_file:
            - .env
    python_app:
        container_name: python_app
        links:
            - "mysql"
        build: ./
        ports:
            - "5001:5001"
        depends_on: 
            - mysql
        