services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
      - '3305:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 2
  
  pythonapp:
    build: .
    command: sh -c "sleep 10s ; python3 ./init.py"
    ports:
    - "5001:5001"
    depends_on:
      - mysql